### ISSUE TITLE
invaild status code revived:200

### ISSUE THREAD

**Issue by hpwriterkyle** [zhou-xiaojian/douyin-live-java#2]
i did run it but failed and it print

paramInt:1002 paramString:Invalid status code received: 200 Status line: HTTP/1.1 200 OK paramBoolean:false

**Comment by lzooo6811** [comment]
i got same issue

**Comment by 970100646** [comment]
解决了吗

**Comment by hpwriterkyle** [comment]
public static String getWssAddr(String roomId) {
        String response =
HttpUtil.get("http://14.103.95.140:9001/get_wssurl?room_id=" + roomId);
        return JSONObject.parseObject(response).getString("data");
    }
请使用此方法获取ws地址 再替换:)
